# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAppShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('myshopify_domain', models.CharField(editable=False, max_length=255, unique=True)),
                ('token', models.CharField(default=b'00000000000000000000000000000000', editable=False, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('shop_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('token', models.CharField(default=b'00000000000000000000000000000000', editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Countnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('sun_today', models.CharField(max_length=20, null=True)),
                ('rain_today', models.CharField(max_length=20, null=True)),
                ('wind_today', models.CharField(max_length=20, null=True)),
                ('snow_today', models.CharField(max_length=20, null=True)),
                ('sun_tomorrow', models.CharField(max_length=20, null=True)),
                ('rain_tomorrow', models.CharField(max_length=20, null=True)),
                ('wind_tomorrow', models.CharField(max_length=20, null=True)),
                ('snow_tomorrow', models.CharField(max_length=20, null=True)),
                ('sun_week', models.CharField(max_length=20, null=True)),
                ('rain_week', models.CharField(max_length=20, null=True)),
                ('wind_week', models.CharField(max_length=20, null=True)),
                ('snow_week', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=127, null=True)),
                ('country', models.CharField(max_length=127, null=True)),
                ('first_name', models.CharField(max_length=127, null=True)),
                ('addr_id', models.CharField(max_length=127, null=True)),
                ('last_name', models.CharField(max_length=127, null=True)),
                ('phone', models.CharField(max_length=18, null=True)),
                ('province', models.CharField(max_length=54, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('province_code', models.CharField(max_length=5, null=True)),
                ('country_code', models.CharField(max_length=5, null=True)),
                ('email', models.CharField(max_length=127, null=True)),
                ('total_spent', models.CharField(max_length=127, null=True)),
                ('created_at', models.CharField(max_length=54, null=True)),
                ('updated_at', models.CharField(max_length=54, null=True)),
                ('today', models.CharField(max_length=255, null=True)),
                ('tomorrow', models.CharField(max_length=255, null=True)),
                ('week', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, null=True)),
                ('order_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('items', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('city_sec', models.CharField(max_length=255, null=True)),
                ('today_condition', models.CharField(max_length=255, null=True)),
                ('tomorrow_condition', models.CharField(max_length=255, null=True)),
                ('week_condition', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
