# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
