# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170524_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='addr_id',
        ),
    ]
