# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170524_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('city_sec', models.CharField(max_length=255, null=True)),
                ('today_condition', models.CharField(max_length=255, null=True)),
                ('tomorrow_condition', models.CharField(max_length=255, null=True)),
                ('week_condition', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
